- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Remove molecule test directories
    ansible.builtin.file:
      path: /tmp/molecule_test
      state: absent
    register: molecule_dir_removal
  - name: Log molecule directory removal
    ansible.builtin.debug:
      msg: Removed molecule test directory at /tmp/molecule_test
